fix: add back types for TypeScript
The current definitions of the packages exposed under `@typescript-eslint/*` is missing the `types` field for legacy setup of TypeScript.

Here is an example to highlight the issue with a project started from scratch:

```
mkdir my-project && cd my-project
npm init -y
npm i typescript @typescript-eslint/utils
echo "import {} from '@typescript-eslint/utils'" > main.ts
npx tsc main.ts
```

The script above will fail with:

```txt
main.ts:1:16 - error TS2307: Cannot find module '@typescript-eslint/utils' or its corresponding type declarations.

1 import {} from '@typescript-eslint/utils'
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 1 error in main.ts:1
```

The reason being that by default (except with resolutionMode=node16 or nodenext), TypeScript ignores the exports.type.

My PR suggests to add back the `types`. It will be used by legacy setups while skipped in modern ones in favor of the `exports.type`.